steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/${PROJECT_ID}/khan-flask-app:${SHORT_SHA}', '.']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${PROJECT_ID}/khan-flask-app:${SHORT_SHA}']
  
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'compute'
      - 'instances'
      - 'update-container'
      - '${_INSTANCE_NAME}'
      - '--zone'
      - '${_ZONE}'
      - '--container-image'
      - 'gcr.io/${PROJECT_ID}/khan-flask-app:${SHORT_SHA}'

images:
  - 'gcr.io/${PROJECT_ID}/khan-flask-app:${SHORT_SHA}'